server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource #不配置，默认是com.zaxxer.hikari.HikariDataSource数据源

  redis:
    host: localhost
    port: 6379
    database: 1
    password:

  rabbitmq:
    host: localhost
    virtual-host: /mall
    username: lb
    password: lb
    publisher-confirms: true  #如果对异步消息需要回调必须设置为true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

logging:
  level:
    com.lb.miaosha.dao: debug
